### ISSUE TITLE
Error in 04-1_refitted.Rmd

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#314]
https://github.com/many-speech-analyses/many_analyses/blob/3cd15575aeae781a41d9745a5dcb701cad505696/scripts/r/04-1_refitted.Rmd#L401-L425

I am getting the following error when running that chunk.

<img width="632" alt="Screenshot 2023-01-26 at 10 49 17" src="https://user-images.githubusercontent.com/6429302/214817710-7784d351-1719-4eaf-84b4-7a9a63b9c4eb.png">

**Comment by jvcasillas** [comment]
Fixed via https://github.com/many-speech-analyses/many_analyses/pull/315

**Comment by stefanocoretta** [comment]
Still does not work.

```
! no applicable method for 'nuts_params' applied to an object of class "c('bam', 'gam', 'glm', 'lm')"
```

I think there is a GAM model in there that maybe you don't have on your local copy?

**Comment by jvcasillas** [comment]
fixed (for real, I think) via https://github.com/many-speech-analyses/many_analyses/pull/316
